MVC/Good Day/Models/Calendario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Good_Day.Models
{
    public class Calendario
    {
    }
}

MVC/Good Day/Controllers/HomeController.cs
using Good_Day.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Good_Day.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Home()
        {
            LibretaManager manager = new LibretaManager();
            List<Libreta> libretas = manager.ConsultarLibretas(((Usuario)Session["UsuarioLogueado"]).ID_usuario);
            ViewBag.Libreta = libretas;

            return View(); 
        }
    
    }
}

MVC/Good Day/Controllers/LibretasController.cs
using Good_Day.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Good_Day.Controllers
{
    public class LibretasController : Controller
    {
        // GET: Libreta
        public ActionResult Index()
        {
            return View();
        }
      
        [HttpPost]
        public ActionResult CreateLibreta(string nameLibreta)
        {
            
            Libreta nuevaLibreta = new Libreta();
            nuevaLibreta.NameLibreta = nameLibreta;

            LibretaManager manager = new LibretaManager();
            manager.Insertar(nuevaLibreta,((Usuario)Session["UsuarioLogueado"]).ID_usuario);

            return RedirectToAction("Home", "Home");
        }
        public ActionResult Eliminar(int ID_libreta)
        {
            Libreta eliminarLibreta = new Libreta();
            eliminarLibreta.ID_libreta = ID_libreta;

            LibretaManager manager = new LibretaManager();
            manager.Eliminar(ID_libreta);

            return RedirectToAction("Home", "Home");
        }
    }
}

MVC/Good Day/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Good_Day.Models;

namespace Good_Day.Controllers
{
    public class UsuariosController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }
   

        [HttpPost]
        public ActionResult Register(string nameUsuario, string mail, string password)
        {
            
            Usuario nuevoUsuario = new Usuario();
            nuevoUsuario.NameUsuario = nameUsuario;
            nuevoUsuario.Mail = mail;
            nuevoUsuario.Password = password;
       
            UsuarioManager manager = new UsuarioManager();
            manager.Insertar(nuevoUsuario);
           return DoLogin(mail,password);
            //return RedirectToAction("DoLogin", new { mail, password });

        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DoLogin(string mail, string password)
        {
            UsuarioManager manager = new UsuarioManager();
            Usuario usuario = manager.Validar(mail, password);
            if (usuario != null)
            {
                //ESTÁ BIEN
                Session["UsuarioLogueado"] = usuario;
            }
            else
            {
                //EL USUARIO NO EXISTE O ESTA MAL LA CONTRASEÑA
                TempData["Error"] = "El usuario no existe o está mal la contraseña";
            }

            return RedirectToAction("Home", "Home");
        }

        public ActionResult Logout()
        {
            Session.Clear();
            //Session["UsuarioLogueado"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

MVC/Good Day/Views/Home/Calendario.cshtml
@{
    ViewBag.Title = "Calendario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calendario</h2>

MVC/Good Day/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="menuNota">
    <div class="container-fluid">
        <div class="row centerText">
            <h2 class="Salsa">Libretas</h2>
            <div id="barIcon" class="col-xs-2">
                <nav>
                    <ul>
                        <li id="libreta"><a data-toggle="modal" data-target="#nuevaLibreta" role="button"><span class="icon icon-book" aria-hidden="true"></span></a></li>
                        <li id="calendario"><a href="#" role="button"><span class="icon icon-calendar" aria-hidden="true"></span></a></li>
                        <li id="papelera"><a href="#" role="button"><span class="icon icon-trash-o" aria-hidden="true"></span></a></li>
                    </ul>
                </nav>
            </div>
            <div id="nuevaLibreta" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Crear Libreta</h4>
                        </div>
                        <div class="modal-body">
                            <form action="@Url.Action("CreateLibreta","Libretas")" method="post">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="nameLibreta" placeholder="Nombre Libreta...">
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>

                            <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
                        </div>
                    </div>

                </div>
            </div>
        
            <div class="container-fluid">
                <div class="row">
                    @if (ViewBag.Libreta != null)
                    {
                        foreach (Good_Day.Models.Libreta libreta in ViewBag.Libreta)
                        {
                            <div class="col-xs-5 col-sm-3 col-lg-2">
                                
                                    <a href="@Url.Action("Notas", "Notas", new { libretaID = libreta.ID_libreta})"> 

                                      @*El new {} envia un objeto por parametro a la accion Notas*@
                                        
                                        <div class="boxLibreta">
                                        <h3>@libreta.NameLibreta</h3>
                                        </div>
                                    </a>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MVC/Good Day/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Good Day</title>
    <link href="https://fonts.googleapis.com/css?family=Kalam:300|Salsa" rel="stylesheet">
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/estilo.css" rel="stylesheet" />
    <link href="~/Content/icon.css" rel="stylesheet" />
   
   
</head>
<body>
    <nav class="navbar-azul">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-offset-2 col-xs-8 col-sm-offset-3 col-sm-6 col-md-offset-0 col-md-3 col-lg-offset-0 col-lg-3">
                    <h1 class="Salsa">Good Day</h1>
                </div>
                <div class="col-xs-offset-2 col-xs-8 col-sm-offset-3 col-sm-4 col-md-offset-1 col-md-8 col-lg-offset-3 col-lg-6">
                    <form class="form-inline margin"action="@Url.Action("DoLogin","Usuarios")"method="post" >
                        <div class="form-group">
                            <label for="mail">Email</label>
                            <input type="text" class="form-control" name="mail">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <div class="form-group centerText">
                            <button type="submit" class="btn btn-outline-secondary">Iniciar Sesión</button>
                        </div>
                    </form>
                </div>
                <div class="row">
                    <div class="col-xs-offset-2 col-xs-8 visible-xs visible-sm">
                        <hr />
                        <div class="form-group centerText">
                            <button type="submit" class="btn btn-outline-secondary">Registrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-offset-8 col-md-3 hidden-xs hidden-sm">
                <form class="margin-top" action="@Url.Action("Register","Usuarios")" method = "post"> 
                    <h2>Registro</h2>
                    <div class="form-group">
                        <input type="text" class="form-control" name="nameUsuario" placeholder="Nombre">
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control"  name="mail" placeholder="Mail">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="password" placeholder="Contraseña">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="password2" placeholder="Confirma Contraseña">
                    </div>
                    <div class="form-group centerText">
                        <button type="submit" class="btn btn-outline-secondary">Registrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/miJavaScript.js"></script>
</body>
</html>