MVC/Good Day/Models/Nota.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Good_Day.Models
{
    public class Nota
    {
        public int ID_notas { get; set; }
        public Tag ID_tag { get; set; }
        public string NameNota { get; set; }
        public DateTime Fecha { get; set; }
    }
}

MVC/Good Day/Controllers/NotasController.cs
using Good_Day.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Good_Day.Controllers
{
    public class NotasController : Controller
    {
        // GET: Notas   
        public ActionResult Notas (int libretaID)
        {
          
            //Muestro en la vista de NOTAS
            //se nesecita hacer una consulta para traer Tags al controlador y despues pasarselos a la viewbag de la vista

            TagManager manager = new TagManager();
            List<Tag> tags = manager.ConsultarTags(libretaID);
            ViewBag.Tag = tags;

            //se nesecita hacer una consulta para traer el nombre de la librta al controlador y despues pasarselos a la viewbag de la vista
            
            LibretaManager admin = new LibretaManager();
            Libreta libreta = admin.ConsultarLibreta(libretaID);
            ViewBag.Libreta = libreta;

            NotasManager mostrar = new NotasManager();
            List<Nota> notas = mostrar.ConsultarNotas(libretaID);
            ViewBag.Nota = notas;
            

            return View();

        }
 
        [HttpPost]
        public ActionResult CreateNota(string nameNota, int tagID)
        {
            int libID = (int)Session["ID"]; //le paso la session de ID_libreta

            Nota nuevaNota = new Nota();
            nuevaNota.NameNota = nameNota;

            NotasManager manager = new NotasManager();
            manager.Insertar(nuevaNota, tagID);

            return RedirectToAction("Notas",libID);
        }
    }
}

MVC/Good Day/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Good_Day.Models;


namespace Good_Day.Controllers
{
    public class TagsController : Controller
    {
        // GET: Tag
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateTag(string nameTag)
        {
            int libID = (int)Session["ID"]; //le paso la session de ID_libreta

            Tag nuevatag = new Tag();
            nuevatag.NameTag = nameTag;
                        
            TagManager manager = new TagManager();

            manager.Insertar(nuevatag, libID);


            return RedirectToAction("Notas", "Notas",libID);

        }


    }
}

MVC/Good Day/Views/Notas/Notas.cshtml
@{
    ViewBag.Title = "Notas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="menuNota">
    <div class="container-fluid">
        <div class="row centerText">
           
            <h2 class="Salsa">@ViewBag.Libreta.NameLibreta</h2>
        
            <a href="@Url.Action("Home","Home")" role = "button"><span class="icon-arrow-left arrow-back" aria-hidden="true"></span></a>    
            <div id="barIcon" class="col-xs-2">
                <nav>
                    <ul>
                        <li id="tag"><a data-toggle="modal" data-target="#nuevaTag" role="button"><span class="icon icon-tag" aria-hidden="true"></span></a></li>
                        <li id="calendario"><a href="#" role="button"><span class="icon icon-calendar" aria-hidden="true"></span></a></li>
                        <li id="papelera"><a href="#" role="button"><span class="icon icon-trash-o" aria-hidden="true"></span></a></li>
                 
                    </ul>
                </nav>
            </div>
            @*Recibo los elementos desde la accion Notas del controlador Notas*@
            <div class="container-fluid">
                <div class="row">
                    @if (ViewBag.Tag != null)
                    {
                        foreach (Good_Day.Models.Tag tag in ViewBag.Tag)
                        {

                          
                            <div class="col-xs-5 col-sm-3 col-lg-2">
                                <div class="boxTag">
                                    <h4>@tag.NameTag</h4>
                                    <hr class="borde">
                                    <ul class="lista">
                                       
                                        @if (ViewBag.Nota != null)
                                        {
                                            foreach (Good_Day.Models.Nota nota in ViewBag.Nota)

                                            {
                                                
                                                <li class="boxNota"><a href="#">@nota.NameNota</a></li>
                                            }
                                        }
 
                                        <li><a class="addNotaa" href="#" id="id-@tag.ID_tag">añadir nota...</a></li>
                                    </ul>
                                    
                                        <form id="divForm-@tag.ID_tag" class="form-inline formAddNota" action="@Url.Action("CreateNota", "Notas", new {tagID = tag.ID_tag })" method="post">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="nameNota" placeholder="Escribe tu nota...">
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-info">Guardar</button>
                                            </div>
                                        </form>
                                    


                                </div>
                            </div>
                        }
                    }

                </div>
            </div>

            <!--Modal del Tag-->
            <div id="nuevaTag" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Crear Tag</h4>
                        </div>
                        
                        <div class="modal-body">
                            <form action="@Url.Action("CreateTag","Tags")" method="post">
                                <div class="form-group">    
                                    <input type="text" class="form-control" name="nameTag" placeholder="Nombre Tag...">
        
                                </div>
                            </form>
                        </div>
                        
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>